version: '3.1'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    command: npm run start:prod
    depends_on:
      - mongo
    restart: always
  mongo:
    container_name: mongo
    image: mongo:7.0
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - '/data/server/data/db:/data/db'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: 1234
  mongo-express:
    container_name: mongo-express
    image: mongo-express:1-20
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
      ME_CONFIG_MONGODB_URL: mongodb://user:1234@mongo:27017/